{
 "title": "APC UPS Dashboard",
 "description": "Monitor your APC UPS statuses, such as blackouts and electrical noise over time.",
 "tags": [
  "APC",
  "apcupsd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UPS Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Total Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "UPS Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Battery Time Left",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds"
    }
   ]
  },
  {
   "title": "Current Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Cumulative Time On Battery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_cumulative_time_on_seconds_total"
    }
   ]
  },
  {
   "title": "Info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "apcupsd_info", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Nominal Power Watts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_apcupsd_nominal_power_watts"
    }
   ]
  },
  {
   "title": "Last Selftest",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "apcupsd_apcupsd_last_selftest" }
   ]
  },
  {
   "title": "Last Transfer On Battery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_apcupsd_last_transfer_on_battery * 1000"
    }
   ]
  },
  {
   "title": "Last Transfer Off Battery",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_apcupsd_last_transfer_off_battery * 1000"
    }
   ]
  },
  {
   "title": "Number Of Total Transfers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "apcupsd_battery_number_transfers_total"
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_line_volts", "legendFormat": "actual" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_nominal_volts", "legendFormat": "nominal" },
    { "expr": "apcupsd_battery_volts", "legendFormat": "actual" }
   ]
  }
 ]
}